name: benchmark

on:
  pull_request:

jobs:
  tests:
    name: benchmark
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
        with:
          path: pull-request

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: pull-request-base

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: cache
        id: cache
        uses: actions/cache@v3
        with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              pull-request/target/
              pull-request-base/target/
            key: bench-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install hyperfine
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install hyperfine

      - name: bench ( pull-request-base )
        run: |
          cd pull-request-base
          hyperfine --runs 30 --warmup 5 -i "cargo test -r symfony"

      - name: bench ( pull-request )
        run: |
          cd pull-request
          hyperfine --runs 30 --warmup 5 -i "cargo test -r symfony"
